---
apiVersion: v1
kind: Service
metadata:
  name: demohttp-backend
  labels:
    app: demohttp-backend
spec:
  ports:
  - port: 8080
    targetPort: http
    name: http
  selector:
    app: demohttp-backend
---
# This tells the prometheus operator instance to monitor this service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-http-backend
  labels:
    app: demohttp-backend
    monitoring: promop
spec:
  selector:
    matchLabels:
      app: demohttp-backend
  endpoints:
  - port: http
    path: "/metrics"
    interval: 15s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demohttp-backend
  labels:
    app: demohttp-backend
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demohttp-backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: demohttp-backend
    spec:
      containers:
      - name: demohttp-backend
        image: jwenz723/demohttp-backend:flux-sync-9-g51e6e1e
        args:
        - "-addr=:8080"
        ports:
        - name: http
          containerPort: 8080
